### ISSUE TITLE
Formal verification

### ISSUE THREAD

**Issue by colin-morpho** [morpho-org/pre-liquidation#13]
Meta issue to track the verification progress and requirements.

## Properties:
- [x] reentrancy safety, see #14 and #15;
- [x] immutability property, see #16 and #25;
- [x] revert checks, see #26 and #37 ;
- [x] ranges, see [comment](https://github.com/morpho-org/pre-liquidation/pull/32#discussion_r1777434013), see #89 ;
- [x] liveness, i.e. `preLiquidate` always repays, see #35 and #38 ;
- [x] liveness, i.e. `preLiquidate` can be called with repaid `assets` or `shares`, see #71  and #72;
- [x] ~~meta-property pre-liquidation doesn't degrade position~~ abandoned, see #94.
